[package]
name = "flutter_bloc_architecture"
version = "0.0.3"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
heck = "0.5.0"
plist = "1.7.0"
regex = "1.11.1"

[profile.release]
lto = true
