mod app_theme_template;
mod injector_template;
mod lints_template;
mod main_template;
mod router_template;
pub use app_theme_template::create_app_theme_file;
pub use injector_template::create_injector_file;
pub use lints_template::lints_template;
pub use main_template::create_main_file;
pub use router_template::create_router_file;
